
data_dir: data
model_dir: models
result_dir: results

gpu_device: '0'

img_rows: 55
img_cols: 47
img_color: 3
numb_classes: 1283

poi_data_file: sunglasses_poisoned_data.h5
val_data_file: clean_validation_data.h5
test_data_file: clean_test_data.h5


random_seed: 123

